// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proppy.API.Persistence.Contexts;

namespace Proppy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210508035236_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proppy.API.Domain.Models.Employee", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasMaxLength(19)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date")
                        .HasMaxLength(16);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Phone_No")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Position_Code")
                        .IsRequired();

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(16)")
                        .HasMaxLength(16);

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("Phone_No")
                        .IsUnique();

                    b.HasIndex("Photo")
                        .IsUnique();

                    b.HasIndex("Position_Code");

                    b.ToTable("Employees");

                    b.HasData(
                        new { ID = 1L, DOB = new DateTime(1970, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc@gmail.com", Gender = "F", Name = "Mary Tan", Phone_No = "0161234567", Photo = "https://picsum.photos/501", Position_Code = "A", Remarks = "", Salary = 5000m },
                        new { ID = 2L, DOB = new DateTime(1971, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz@yahoo.com", Gender = "M", Name = "Aliasgar", Phone_No = "+60161234568", Photo = "https://picsum.photos/502", Position_Code = "B", Remarks = "", Salary = 3500m },
                        new { ID = 3L, DOB = new DateTime(1972, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc2@gmail.com", Gender = "M", Name = "Justin Biieber", Phone_No = "0161234569", Photo = "https://picsum.photos/503", Position_Code = "B", Remarks = "", Salary = 3300m },
                        new { ID = 4L, DOB = new DateTime(1973, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz2@yahoo.com", Gender = "M", Name = "Chow Yun Fatt", Phone_No = "0161234570", Photo = "https://picsum.photos/504", Position_Code = "C", Remarks = "", Salary = 2800m },
                        new { ID = 5L, DOB = new DateTime(1974, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc3@gmail.com", Gender = "F", Name = "Angela Baby", Phone_No = "0161234571", Photo = "https://picsum.photos/505", Position_Code = "D", Remarks = "", Salary = 2700m },
                        new { ID = 6L, DOB = new DateTime(1975, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz3@yahoo.com", Gender = "M", Name = "Mohd Rizal", Phone_No = "+80161234569", Photo = "https://picsum.photos/506", Position_Code = "C", Remarks = "", Salary = 2500m },
                        new { ID = 7L, DOB = new DateTime(1976, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc4@gmail.com", Gender = "M", Name = "Ken yoong", Phone_No = "+50161234571", Photo = "https://picsum.photos/507", Position_Code = "D", Remarks = "", Salary = 2550m },
                        new { ID = 8L, DOB = new DateTime(1977, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz4@yahoo.com", Gender = "M", Name = "Willson Wong", Phone_No = "+44161234533", Photo = "https://picsum.photos/508", Position_Code = "A", Remarks = "", Salary = 5500m },
                        new { ID = 9L, DOB = new DateTime(1978, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc5@gmail.com", Gender = "F", Name = "Vivian Chong", Phone_No = "0161234575", Photo = "https://picsum.photos/509", Position_Code = "F", Remarks = "", Salary = 7000m },
                        new { ID = 10L, DOB = new DateTime(1979, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz5@yahoo.com", Gender = "F", Name = "Shirley Tan Wai Ling", Phone_No = "0161234576", Photo = "https://picsum.photos/510", Position_Code = "E", Remarks = "", Salary = 8000m },
                        new { ID = 11L, DOB = new DateTime(1980, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc9@gmail.com", Gender = "F", Name = "Mary Tan 2", Phone_No = "01612345672", Photo = "https://picsum.photos/511", Position_Code = "A", Remarks = "", Salary = 5000m },
                        new { ID = 12L, DOB = new DateTime(1981, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz9@yahoo.com", Gender = "M", Name = "Aliasgar 2", Phone_No = "+601612345682", Photo = "https://picsum.photos/512", Position_Code = "B", Remarks = "", Salary = 3500m },
                        new { ID = 13L, DOB = new DateTime(1982, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc29@gmail.com", Gender = "M", Name = "Justin Biieber 2", Phone_No = "01612345692", Photo = "https://picsum.photos/513", Position_Code = "B", Remarks = "", Salary = 3300m },
                        new { ID = 14L, DOB = new DateTime(1983, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz29@yahoo.com", Gender = "M", Name = "Chow Yun Fatt 2", Phone_No = "01612345702", Photo = "https://picsum.photos/514", Position_Code = "C", Remarks = "", Salary = 2800m },
                        new { ID = 15L, DOB = new DateTime(1984, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc39@gmail.com", Gender = "F", Name = "Angela Baby 2", Phone_No = "01612345712", Photo = "https://picsum.photos/515", Position_Code = "D", Remarks = "", Salary = 2700m },
                        new { ID = 16L, DOB = new DateTime(1985, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz39@yahoo.com", Gender = "M", Name = "Mohd Rizal 2", Phone_No = "+801612345692", Photo = "https://picsum.photos/516", Position_Code = "C", Remarks = "", Salary = 2500m },
                        new { ID = 17L, DOB = new DateTime(1986, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc49@gmail.com", Gender = "M", Name = "Ken yoong 2", Phone_No = "+501612345712", Photo = "https://picsum.photos/517", Position_Code = "D", Remarks = "", Salary = 2550m },
                        new { ID = 18L, DOB = new DateTime(1987, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz49@yahoo.com", Gender = "M", Name = "Willson Wong 2", Phone_No = "+441612345332", Photo = "https://picsum.photos/518", Position_Code = "A", Remarks = "", Salary = 5500m },
                        new { ID = 19L, DOB = new DateTime(1988, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "abc59@gmail.com", Gender = "F", Name = "Vivian Chong 2", Phone_No = "01612345752", Photo = "https://picsum.photos/519", Position_Code = "G", Remarks = "", Salary = 7000m },
                        new { ID = 20L, DOB = new DateTime(1989, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "xyz59@yahoo.com", Gender = "F", Name = "Shirley Tan Wai Ling 2", Phone_No = "01612345762", Photo = "https://picsum.photos/520", Position_Code = "H", Remarks = "", Salary = 8000m }
                    );
                });

            modelBuilder.Entity("Proppy.API.Domain.Models.Position", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new { Code = "A", Description = "Senior Manager" },
                        new { Code = "B", Description = "Manager" },
                        new { Code = "C", Description = "Engineer" },
                        new { Code = "D", Description = "Designer" },
                        new { Code = "E", Description = "CEO" },
                        new { Code = "F", Description = "COO" },
                        new { Code = "G", Description = "CTO" },
                        new { Code = "H", Description = "CMO" }
                    );
                });

            modelBuilder.Entity("Proppy.API.Domain.Models.Employee", b =>
                {
                    b.HasOne("Proppy.API.Domain.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("Position_Code")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
