# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ProppyAPITest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.807'

    - name: Build with dotnet
      working-directory: ./backend/Proppy.API
      run: dotnet build --configuration Release

    - name: dotnet publish
      working-directory: ./backend/Proppy.API
      run: dotnet publish -c Release -o ./backend/Proppy.API/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ./backend/Proppy.API/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ProppyAPITest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e468f5fb53834deea0efe78e0da38235 }}
        package: .